# Generated by Django 4.2.4 on 2023-09-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(default='Nome Padrão', max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('numero', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FilmeFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('diretor', models.CharField(default='Nome Padrão', max_length=100)),
                ('ano', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
