# Generated by Django 4.2.4 on 2023-09-02 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_comidafavorita_crud_filme_favorito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud',
            name='comida_favorita',
        ),
        migrations.DeleteModel(
            name='ComidaFavorita',
        ),
    ]
