# Generated by Django 4.2.4 on 2023-09-02 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_remove_crud_comida_favorita_delete_comidafavorita'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='ano_do_filme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ano_do_filme_set', to='crud.filmefavorito'),
        ),
        migrations.AlterField(
            model_name='crud',
            name='filme_favorito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filme_favorito_set', to='crud.filmefavorito'),
        ),
    ]
