# Generated by Django 4.2.4 on 2023-09-02 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_crud_ano_do_filme_alter_crud_filme_favorito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud',
            name='ano_do_filme',
        ),
    ]
