# Generated by Django 4.2.4 on 2023-09-02 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_remove_crud_ano_do_filme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='filme_favorito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud.filmefavorito'),
        ),
    ]
